# Generated by Django 3.0.8 on 2020-08-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
