# Generated by Django 3.0.8 on 2020-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0003_auto_20200825_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comments',
            name='is_comment',
            field=models.CharField(default='c', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_dates',
            name='is_date',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_freespaces',
            name='is_freespace',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_ideas',
            name='is_idea',
            field=models.CharField(default='i', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_questions',
            name='is_question',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_subjects',
            name='is_subject',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_terms',
            name='is_term',
            field=models.CharField(default='te', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_trans',
            name='is_tran',
            field=models.CharField(default='tr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_comments',
            name='is_comment',
            field=models.CharField(default='c', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_dates',
            name='is_date',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_freespaces',
            name='is_freespace',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_ideas',
            name='is_idea',
            field=models.CharField(default='i', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_questions',
            name='is_question',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_subjects',
            name='is_subject',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_terms',
            name='is_term',
            field=models.CharField(default='tr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_trans',
            name='is_tran',
            field=models.CharField(default='tr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_comments',
            name='is_comment',
            field=models.CharField(default='c', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_dates',
            name='is_date',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_freespaces',
            name='is_freespace',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_ideas',
            name='is_idea',
            field=models.CharField(default='i', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_questions',
            name='is_question',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_subjects',
            name='is_subject',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_terms',
            name='is_term',
            field=models.CharField(default='te', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_trans',
            name='is_tran',
            field=models.CharField(default='tr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_comments',
            name='is_comment',
            field=models.CharField(default='c', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_dates',
            name='is_date',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_freespaces',
            name='is_freespace',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_ideas',
            name='is_idea',
            field=models.CharField(default='i', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_questions',
            name='is_question',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_subjects',
            name='is_subject',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_terms',
            name='is_term',
            field=models.CharField(default='te', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_trans',
            name='is_tran',
            field=models.CharField(default='tr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_comments',
            name='is_comment',
            field=models.CharField(default='c', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_dates',
            name='is_date',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_freespaces',
            name='is_freespace',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_ideas',
            name='is_idea',
            field=models.CharField(default='i', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_questions',
            name='is_question',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_subjects',
            name='is_subject',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_terms',
            name='is_term',
            field=models.CharField(default='te', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_trans',
            name='is_tran',
            field=models.CharField(default='tr', max_length=100),
            preserve_default=False,
        ),
    ]
