# Generated by Django 3.0.8 on 2020-08-31 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0007_auto_20200827_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='addUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.TextField()),
                ('update_for', models.CharField(max_length=255, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser')),
            ],
        ),
    ]
