# Generated by Django 3.0.8 on 2020-09-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0010_addupdate_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addupdate',
            name='share',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
