# Generated by Django 3.0.8 on 2020-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0014_auto_20200913_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
