# Generated by Django 3.0.8 on 2020-09-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0015_auto_20200913_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
