# Generated by Django 3.0.8 on 2020-09-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0016_auto_20200913_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comments',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_dates',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_freespaces',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_ideas',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_questions',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_subjects',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_terms',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_trans',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_comments',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_dates',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_freespaces',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_ideas',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_questions',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_subjects',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_terms',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_trans',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_comments',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_dates',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_freespaces',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_ideas',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_questions',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_subjects',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_terms',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcast_trans',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_comments',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_dates',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_freespaces',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_ideas',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_questions',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_subjects',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_terms',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture_trans',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_comments',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_dates',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_freespaces',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_ideas',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_questions',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_subjects',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_terms',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_trans',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='readernote.MyUser'),
            preserve_default=False,
        ),
    ]
