# Generated by Django 3.0.8 on 2020-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readernote', '0019_myuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='twitter_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
